#!/usr/bin/env python3
"""Build the Veeva API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Vault Query Language': 'Query Language',
}

LINES = [
    {
        "name": 'Veeva Vault',
        "color": '#E51E26',
        "closed": True,
        "stations": [
        ('Vault API', (640, 260)),
        ('Java SDK', (840, 460)),
        ('Vault Query Language', (640, 660)),
        ('Direct Data', (440, 460)),
        ],
    },
]

URL_OVERRIDES = {
    'Vault API': 'https://apis.apis.io/apis/veeva/veeva-vault-api/',
    'Java SDK': 'https://apis.apis.io/apis/veeva/veeva-vault-java-sdk/',
    'Vault Query Language': 'https://apis.apis.io/apis/veeva/veeva-vault-query-language/',
    'Direct Data': 'https://apis.apis.io/apis/veeva/veeva-vault-direct-data-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Veeva API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: veeva/openapi · github.com/api-evangelist/veeva',
        out_dir=Path(__file__).resolve().parent,
        out_basename='veeva-subway-map',
        provider_id='veeva',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
